config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  as :user do
    get "sign_in" => "users/sessions#new"
    post "sign_in" => "users/sessions#create"
    get "sign_out" => "users/sessions#destroy"
    get "sign_up" => "users/registrations#new"
    post "sign_up" => "users/registrations#create"
  end
  devise_scope :user do
    authenticated :user do
      root 'departments#index', as: :authenticated_root
      resources 'departments'
      resources 'projects'
      resources 'users_projects'
      resources 'users_departments'
      resources :users
      resource :profile, only: [:show, :edit, :update]
      post 'change_leader' => 'projects#update_leader'
      get 'change_leader' => 'projects#change_leader'
      # get 'users_projects_detail' => 'projects#users_projects_detail'
      get 'user_profile' => 'users#info'
      get 'done_project' => 'projects#done_project'
      get 'restart_project' => 'projects#restart_project'
      get 'click' => 'departments#click'
      get 'changeStatus' => 'projects#changeStatus'
      get 'projects_done' => 'projects#projects_done'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :project_manager, foreign_key: :user_id, class_name: User.to_s, optional: true

  has_many :projects
  has_many :users_departments
  has_many :users, through: :users_departments

  validates :name, uniqueness: true, presence: true
  # validate :pm_user_validation, on: :update

  def maybe_pm_users
    User.where(id: users.ids)
  end

  def user_in_department
    User.where(id: users.ids)
  end

  def free_user
    User.where.not(id: UsersDepartment.select(:user_id))
  end

  # def pm_user_validation
  #   return if users.exists?(id: user_id)
  #   errors.add(:user_id, "can thuoc danh sach users")
  # end

  def pm
    project_manager
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  # before_action :IsAdmin?, only: [:new, :create, :destroy]
  layout "dashboard"

  def index
    user = current_user
    if user.information.admin? || user.information.hr?
      @departments = Department.all
    else
      @departments = [current_user.department]
    end
  end

  def show
    @department = Department.find(params[:id])
    authorize @department
  end

  def new
    @department = Department.new
    authorize @department
  end

  def create
    authorize Department.none
    @department = Department.new(name: params['department']['name'], user_id: nil)
    @department.save
    redirect_to action: :index
  end

  def edit
    @department = Department.find(params[:id])
    @current_PM = @department.project_manager
    authorize @department
  end

  def update
    authorize Department.none
    @department = Department.find(params[:id])
    if @department.update(name: params['department']['name'], user_id: params['department']['user_id'])
      redirect_to action: :index
    else
      render :edit
    end
  end

  def destroy
    authorize Department.none
    @department = Department.find(params[:id])
    UsersDepartment.delete(@department.users_departments.ids)
    @department.projects.update(department_id: nil)
    Department.destroy(params[:id])
  end

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_detail.erb
<p style="color: #2f9bcd" class="col-6">Department have <%= @department.users.length %> member</p>

<% if @department.users.blank? %>
  <h4 class="ml-5">Department have 0 member</h4>
<% else %>
  <table class="table">
    <thead class="thead-dark">
    <th>#</th>
    <th>Name</th>
    <th>Email</th>
    <% if policy(@department).information? %>
      <th>Address</th>
      <th>Phone</th>
      <th>Date of Birth</th>
    <% end %>
    <th>role</th>
    <% if policy(@department).operation? %>
      <th colspan="2">Operation</th>
    <% end %>

    </thead>
    <% @department.users.each_with_index do |user, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= user.information.name %></td>
        <td><%= user.email %></td>
        <% if policy(@department).information? %>
          <td><%= user.information.address %></td>
          <td><%= user.information.phone %></td>
          <td><%= user.information.date_of_birth.strftime("%d/%m/%Y") %></td>
        <% end %>
        <% if @department.user_id == user.id %>
          <td style="color: red"> PM </td>
        <% else %>
          <td><%= user.information.role %></td>
        <% end %>

        <% if policy(@department).operation? %>
          <% if policy(@department).pm? %>
            <td></td>
          <% else %>
            <td><%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-dash-fill" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M11 7.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z"/>
  <path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
</svg> Delete'), users_department_path(user), data: { "turbo-method": :delete, turbo_confirm: 'Are you certain you want to delete this?' }, class: 'btn btn-danger' %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/departments/_form.html.erb
<%= form_with(model: @department, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :Department_name %>
    <%= f.text_field :name, class: 'form-control col-md-7' %>
  </div>
  <div class="form-group">
    <%= f.label :PM %>
    <%= f.select :user_id, @department.maybe_pm_users.map { |user| [user.email, user.id] }, {},
                 class: "form-control col-md-7" %>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/departments/edit.html.erb
<%#=render "layouts/navbar" %>
<% provide(:button_text, 'Update department') %>
<h1>Edit Department</h1>
<hr>
<%= render 'form' %>

<h2 class="mt-5">Users in department</h2>
<%#= render 'detail' %>

app/views/departments/index.html.erb
<h1>Department</h1>
<%= @department %>
<% if policy(@departments).edit? %>
  <div class="mb-4">
    <div class="mt-4">
      <%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-plus-square" viewBox="0 0 16 16">
  <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
  <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/>
</svg> Add department'), new_department_path, class: 'btn btn-success mr-3' %>
    </div>
  </div>
<% end %>
<% if @departments.blank? %>
<% else %>
  <table class="table">
    <thead class="thead-dark">
    <th>#</th>
    <th>Name department</th>
    <th>Member</th>
    <th>Name PM</th>
    <% if policy(Department.none).edit? %>
      <th colspan="3">Action</th>
    <% end %>
    </thead>
    <% @departments.each_with_index do |department, index| %>
      <tr>
        <td><%= index + 1 %></td>
        <td><%= link_to department.name, department_path(department.id) %></td>
        <td><%= department.users.length %></td>
        <td style="color: crimson"><%= department.project_manager.nil? ? 'None PM' : department.project_manager.information.name %></td>
        <% if policy(department).edit? %>
          <td><%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus" viewBox="0 0 16 16">
  <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0zm4 8c0 1-1 1-1 1H1s-1 0-1-1 1-4 6-4 6 3 6 4zm-1-.004c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664h10z"></path>
  <path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"></path>
</svg> Add user to department'), new_users_department_path(id: department.id), class: 'btn btn-success' %></td>
          <td><%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
  <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
  <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
</svg>
 Edit'), { :action => 'edit', :id => department.id }, class: 'btn btn-warning' %></td>
          <td><%= link_to raw('<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
</svg> Delete'), department_path(department.id), data: { "turbo-method": :delete, turbo_confirm: :'Are you sure?' }, class: "btn btn-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/departments/new.html.erb
<h1>Add New Department</h1>
<%= form_with(model: @department, local: true) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control col-md-7' %>
  </div>
  <%= f.submit 'Add department', class: "btn btn-primary" %>
<% end %>

app/views/departments/show.html.erb
<h3>Employee in <%= @department.name %> department</h3>

<%= render 'detail' %>