config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  as :user do
    get "sign_in" => "users/sessions#new"
    post "sign_in" => "users/sessions#create"
    get "sign_out" => "users/sessions#destroy"
    get "sign_up" => "users/registrations#new"
    post "sign_up" => "users/registrations#create"
  end
  devise_scope :user do
    authenticated :user do
      root 'departments#index', as: :authenticated_root
      resources 'departments'
      resources 'projects'
      resources 'users_projects'
      resources 'users_departments'
      resources :users
      resource :profile, only: [:show, :edit, :update]
      post 'change_leader' => 'projects#update_leader'
      get 'change_leader' => 'projects#change_leader'
      # get 'users_projects_detail' => 'projects#users_projects_detail'
      get 'user_profile' => 'users#info'
      get 'done_project' => 'projects#done_project'
      get 'restart_project' => 'projects#restart_project'
      get 'click' => 'departments#click'
      get 'changeStatus' => 'projects#changeStatus'
      get 'projects_done' => 'projects#projects_done'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/users_department.rb
class UsersDepartment < ApplicationRecord
  belongs_to :user
  belongs_to :department

  validates :user_id, presence: true
  validates :department_id, presence: true
end

app/controllers/users_departments_controller.rb
class UsersDepartmentsController < ApplicationController
  layout "dashboard"

  def new
    @department = Department.find(params[:id])
    @users = @department.free_user
    @users_department = UsersDepartment.new
    authorize @users_department
  end

  def create
    if User.find(params['users_department']['user_id']).department.nil?
      UsersDepartment.create(user_id: params['users_department']['user_id'], department_id:  params['department_id'])
    end
    redirect_to department_path(params['department_id'])
  end

  def destroy

    user = User.find(params[:id])

    user.projects.where(user_id: user.id, status: false).update(user_id: nil)

    UsersProject.delete(UsersProject.where(project_id: user.projects.where(status: false).ids, user_id: user.id).ids)

    if user.department.user_id == user.id
      user.department.update(user_id: nil)
    end
    UsersDepartment.delete(UsersDepartment.where(user_id: params[:id]).ids)

  end

  def show
    @department = UsersDepartment.where(user_id: params[:id])[0]
    @user = User.find(params[:id])
    @projects = UsersProject.where(user_id: params[:id])
    @done_projects = []
    @doing_projects = []
    @projects.each do |project|
      project = Project.find(project.project_id)
      if project.status == true && project.department_id == @department.department_id
        @done_projects.push(project)
      else
        @doing_projects.push(project)
      end
    end
  end

end

app/helpers/users_department_helper.rb
module UsersDepartmentHelper
end

app/helpers/users_departments_helper.rb
module UsersDepartmentsHelper
end

app/views/users_departments/_form.html.erb
<%= form_with(model: @users_department, method: :post, local: true) do |f| %>

  <div>
    <%= f.label :user_id %>
    <%= f.select :user_id, options_for_select(@users.map{|user| [user.email, user.id] }),{}, class: "form-control col-md-7"%>
  </div>

  <input type="hidden" name="department_id" value="<%= @department.id %>">

  <%= f.submit yield(:button_text), class: "btn btn-primary mt-2" %>
<% end %>

app/views/users_departments/new.html.erb
<%#=render "layouts/navbar" %>
<% provide(:button_text, 'Add User') %>
<h1>Add New User To <%= @department.name %></h1>
<%= render 'form' %>

app/views/users_departments/show.html.erb
<h3> Are you sure you want to kick this employee?</h3>
<strong>Name: </strong> <%= @user.information.name %><br/>
<strong>Email: </strong> <%= @user.email %><br/>
<strong>Role: </strong> <%= @user.information.role %><br/>
<strong>Birthday: </strong> <%= @user.information.date_of_birth.strftime("%d/%m/%Y") %><br/>
<strong>Address: </strong> <%= @user.information.address %><br/>
<strong>Phone: </strong> <%= @user.information.phone %><br/>
<strong>Day join department: </strong> <%= @department.created_at.strftime("%d/%m/%Y") %><br/>
<strong>Projects participated: </strong> <%= @done_projects.length %><br/>
<strong>Project is participating: </strong> <%= @doing_projects.length %><br/>
<br>
<p style="color: crimson"><i> Kicking this employee will kick him out of the projects this employee is working on !!</i>
</p>
<%= link_to 'Kick', users_department_path(@user.id),
            data: { "turbo-method": :delete, turbo_confirm: 'Are you certain you want to delete this?' }, class: 'btn btn-danger' %>