config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  as :user do
    get "sign_in" => "users/sessions#new"
    post "sign_in" => "users/sessions#create"
    get "sign_out" => "users/sessions#destroy"
    get "sign_up" => "users/registrations#new"
    post "sign_up" => "users/registrations#create"
  end
  devise_scope :user do
    authenticated :user do
      root 'departments#index', as: :authenticated_root
      resources 'departments'
      resources 'projects'
      resources 'users_projects'
      resources 'users_departments'
      resources :users
      resource :profile, only: [:show, :edit, :update]
      post 'change_leader' => 'projects#update_leader'
      get 'change_leader' => 'projects#change_leader'
      # get 'users_projects_detail' => 'projects#users_projects_detail'
      get 'user_profile' => 'users#info'
      get 'done_project' => 'projects#done_project'
      get 'restart_project' => 'projects#restart_project'
      get 'click' => 'departments#click'
      get 'changeStatus' => 'projects#changeStatus'
      get 'projects_done' => 'projects#projects_done'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :project_manager, foreign_key: :user_id, class_name: User.to_s, optional: true

  has_many :projects
  has_many :users_departments
  has_many :users, through: :users_departments

  validates :name, uniqueness: true, presence: true
  # validate :pm_user_validation, on: :update

  def maybe_pm_users
    User.where(id: users.ids)
  end

  def user_in_department
    User.where(id: users.ids)
  end

  def free_user
    User.where.not(id: UsersDepartment.select(:user_id))
  end

  # def pm_user_validation
  #   return if users.exists?(id: user_id)
  #   errors.add(:user_id, "can thuoc danh sach users")
  # end

  def pm
    project_manager
  end
end

app/models/information.rb
class Information < ApplicationRecord

  enum role: { :admin => 1, :hr => 2 , :employee => 3 }

  belongs_to :user

  validates :name, presence: true
  validates :address, presence: true
  validates :date_of_birth, presence: true
  validates :phone, presence: true
  validates :role, presence: true

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user, foreign_key: :user_id, class_name: User.to_s, optional: true

  has_many :users_projects
  has_many :users, through: :users_projects

  belongs_to :department, foreign_key: :department_id, class_name: Department.to_s, optional: true

  validates :name, presence: true

  def pm_dp
    department.pm
  end

  def leader_pj
    user
  end
end

app/models/role.rb
class Role < ApplicationRecord
  # has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :users_projects
  has_many :projects, through: :users_projects

  has_one :information

  has_one :users_department
  has_one :department, through: :users_department


  accepts_nested_attributes_for :information

  def with_information
    build_information if information.nil?
    self
  end

  def free?
    department.blank?
  end
end

app/models/users_department.rb
class UsersDepartment < ApplicationRecord
  belongs_to :user
  belongs_to :department

  validates :user_id, presence: true
  validates :department_id, presence: true
end

app/models/users_project.rb
class UsersProject < ApplicationRecord
  belongs_to :user
  belongs_to :project, foreign_key: :project_id, class_name: Project.to_s

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  layout "dashboard"
  def edit
  end

  def update
    @profile = Information.where(user_id: current_user.id)
    @profile.update(name: params['name'], address: params['address'], phone: params['phone'], date_of_birth: params['dat`e_of_birth'])
    redirect_to action: :show
  end

  def show

  end

  private


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # before_action :IsAdmin?, only: [:create, :new]
  before_action :done?, only: [:change_leader, :destroy, :update_leader]
  layout "dashboard"

  def index
    user = current_user
    if user.information.admin? || user.information.hr?
      @projects = Project.all.where(status: false)
    else
      @projects = current_user.projects.where(status: false)
    end
  end

  def projects_done
    user = current_user
    if user.information.admin? || user.information.hr?
      @projects = Project.all.where(status: true)
    else
      @projects = current_user.projects.where(status: true)
    end
  end

  def new
    @departments = Department.all
    @project = Project.new
  end

  def create
    department_id = params['project']['department_id']
    @department = Department.find(department_id)
    user_id = @department.user_id
    @project = Project.new(name: params['project']['name'], department_id: department_id, user_id: user_id, status: false)
    if @project.save
      PM_to_leader(user_id)
    end
  end

  def users_projects_detail
    session[:id] = params[:id]
    redirect_to users_projects_path
  end

  def change_leader
    @project = Project.find(params[:id])
    authorize @project
  end

  def update_leader
    @project_change = Project.find(params[:id])
    @project_change.update(user_id: params[:user_id])
    redirect_to change_leader_path(params[:id])
  end

  def done_project
    @project = Project.find(params[:id])

    authorize @project

    @project.update(status: true)
    @project.save
    redirect_to action: :changeStatus
  end

  def restart_project
    @project = Project.find(params[:id])
    @project.update(status: false)
    @project.save
    redirect_to action: :changeStatus
  end

  def changeStatus
    if session[:status]
      session[:status] = false
    else
      session[:status] = true
    end
    redirect_to action: :index
  end

  def destroy
    UsersProject.destroy(params[:id])
  end

  private

  def done?
    @project = Project.find(params[:id])
    if @project.status == true
      redirect_to action: :index
    end
  end

  def PM_to_leader(user_id)
    id = Project.last.id
    @users_department = UsersProject.new(project_id: id, user_id: user_id)
    @users_department.save
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  layout "dashboard"

  def edit
    @user = Information.where(user_id: current_user.id)
  end

  def update
    @user = Information.where(user_id: current_user.id)
    # @user.update(params)
  end

  def index
    @users = User.all
    authorize @users
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy

    authorize User.none

    user = User.find(params[:id])

    user.projects.where(user_id: user.id).update(user_id: nil)
    Department.where(user_id: user.id).update(user_id: nil)

    UsersProject.delete(UsersProject.where(project_id: user.projects.ids, user_id: user.id).ids)
    UsersDepartment.delete(UsersDepartment.where(user_id: params[:id]).ids)

    Information.destroy(params[:id])
    User.destroy(params[:id])

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/user_department_helper.rb
module UserDepartmentHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/users_projects_helper.rb
module UsersProjectsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <span class="nav-link nav-link dropdown-toggle navbarDropdown "  role="button" data-toggle="dropdown" aria-expanded="false"><%= current_user.information.name %>(<%= current_user.information.role %>)</span>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Profile', profile_path(current_user.id), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", sign_out_path, method: 'delete', class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Department", departments_path ,class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Project", projects_path ,class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "User", users_path ,class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quanly3</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
        integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
</head>

<body>
<div class="container-fluid">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>
<div class="container" >
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HRM</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <span class="nav-link nav-link dropdown-toggle navbarDropdown " role="button" data-toggle="dropdown" aria-expanded="false"><%= current_user.information.name %>
          (<%= current_user.information.role %>)</span>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to 'Profile', profile_path(current_user.id), class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Logout", sign_out_path, method: 'delete', class: "dropdown-item" %>
        </div>
      </li>
      <li class="nav-item">
        <%= link_to "Department", departments_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Project", projects_path, class: "nav-link" %>
      </li>
      <% if policy(User.all).index? %>
        <li class="nav-item">
          <%= link_to "User", users_path, class: "nav-link" %>
        </li>
      <% end %>

    </ul>
  </div>
</nav>

<p class="notice" style="color: green"><%= notice %></p>
<p class="alert"><%= alert %></p>
</div>
<div class="container">
  <%= yield %>
</div>
</body>
</html>